name: 🐞 Bug Report
description: Create a report to help us improve
title: '[🐞] '
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        ## Before Submitting an Issue

        1. Have you read ImageMapster's [Code of Conduct](https://github.com/jamietre/ImageMapster/blob/main/CODE_OF_CONDUCT.md)? By filing an Issue, you are expected to comply with it, including treating everyone with respect.
        1. Have you read ImageMapster's [Contributing Guidelines](https://github.com/jamietre/ImageMapster/blob/main/CONTRIBUTING.md)?  If not, please review them before filing an issue.
        1. Have you searched [existing issues](https://github.com/jamietre/ImageMapster/issues?q=is%3Aissue+) to see if your issue has already been reported?
        1. Do you want to ask a question? Are you looking for support? **Please do not use the issue tracker for personal support requests.** For questions, how to's, etc, please see the [Support Page](https://github.com/jamietre/ImageMapster/blob/main/SUPPORT.md) for options.

  - type: textarea
    id: description
    attributes:
      description: |
        A clear and concise description of what the bug is including screenshots, if applicable, to help explain the problem. Make sure to add **all the information needed to understand the bug** so that someone can help. If there is not enough information to **easily** understand and reproduce the issue, we'll add the 'needs author feedback' label and close the issue until there is enough information provided.
      label: Describe the bug
    validations:
      required: true

  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a link to a location (e.g., repo, [jsFiddle](https://www.jsfiddle.net), etc.) that reproduces the problem you ran into using the latest version of ImageMapster. Please see the [contributing docs](https://github.com/jamietre/ImageMapster/blob/main/CONTRIBUTING.md) for suggestions on creating a reproduction. A [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) **is required** ([Why?](https://antfu.me/posts/why-reproductions-are-required)). If a report is vague (e.g., just a generic error message) and has no reproduction, it will receive a "needs author feedback" label and the issue closed until there is enough information provided.
      placeholder: Reproduction URL
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to reproduce
      description: Please provide any reproduction steps that may need to be described.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: environment_info
    attributes:
      label: Environment Info
      description: Which device(s), operating system(s) & browser(s) did you experience the issue on?  If multiple, please list all.
      placeholder: |
        1. Windows 11 - Chrome 122.0.6261.129
        2. Windows 11 - Edge 122.0.2365.80
        3. macOS 14.4 - Safari 17.0
        4. Samsung Galaxy S24 - Android 14 - Chrome 122.0.6261.119
    validations:
      required: true

  - type: textarea
    id: behavior_expected
    attributes:
      label: Expected Behavior
      placeholder: |
        A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      description: |
        Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).
    validations:
      required: false
