---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''
---

<!--

Have you read ImageMapster's Code of Conduct? By filing an Issue, you are expected to comply with it, including treating everyone with respect: https://github.com/jamietre/ImageMapster/blob/main/CODE_OF_CONDUCT.md

Have you read ImageMapster's Contributing guidelines?  If not, please review them before filing an issue https://github.com/jamietre/ImageMapster/blob/main/CONTRIBUTING.md

Do you want to ask a question? Are you looking for support? StackOverflow with the imagemapster tag is the best place for getting support: https://stackoverflow.com/questions/tagged/imagemapster

-->

Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'needs author feedback' label and close the issue until there is enough information.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

- OS: [e.g. iOS]
- Browser [e.g. chrome, safari]
- Version [e.g. 22]

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone6]
- OS: [e.g. iOS8.1]
- Browser [e.g. stock browser, safari]
- Version [e.g. 22]

**Additional context**
Any other information you want to share that is relevant to the issue being
reported. This might include the lines of code that you have identified as
causing the bug, and potential solutions (and your opinions on their
merits).
