name: ✨ Feature Request
description: Suggest an idea for this project
title: '[✨] '
labels: new feature
body:
  - type: markdown
    attributes:
      value: |
        ## Before Submitting an Issue

        1. Have you read ImageMapster's [Code of Conduct](https://github.com/jamietre/ImageMapster/blob/main/CODE_OF_CONDUCT.md)? By filing an Issue, you are expected to comply with it, including treating everyone with respect.
        2. Have you read ImageMapster's [Contributing Guidelines](https://github.com/jamietre/ImageMapster/blob/main/CONTRIBUTING.md)?  If not, please review them before filing an issue.
        3. Have you searched [existing issues](https://github.com/jamietre/ImageMapster/issues?q=is%3Aissue+) to see if your issue has already been reported?
        4. Do you want to ask a question? Are you looking for support? **Please do not use the issue tracker for personal support requests.** For questions, how to's, etc, please see the [Support Page](https://github.com/jamietre/ImageMapster/blob/main/SUPPORT.md) for options.

  - type: textarea
    id: description
    attributes:
      description: A clear and concise description of what the problem is and/or why the functionality you're proposing is desired/needed.
      label: Is your feature request related to a problem and/or adding functionality? Please describe
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      description: A clear and concise description of what you want to happen.
      label: Describe the solution you'd like
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      description: A clear and concise description of any alternative solutions or features you've considered.
      label: Describe alternatives you've considered
    validations:
      required: true

  - type: textarea
    id: additional_information
    attributes:
      description: Add any other context or screenshots about the feature request here.
      label: Additional context
    validations:
      required: true
